=== evt-project/evt-builder/js/main/vk.dtd
<!ELEMENT keyboard-group (keyboard+)>
<!ELEMENT keyboard (key-group+)>
<!ELEMENT key-group (key+)>
<!ELEMENT key (#PCDATA)>

<!ATTLIST keyboard code ID #REQUIRED>
<!ATTLIST key-group name CDATA #IMPLIED>
<!ATTLIST key id ID #REQUIRED>

=== evt-project/evt-builder/config/keyboard_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE keyboard-group SYSTEM "vk.dtd">
<!--
    Configuration file for EVT virtual keyboards
    Instructions:
    - to add a new keyboard, simply add a new <keyboard /> tag after the first, specifing the correct
    language code (e.g.: it, en, etc);
    - add one or more key-group with <key-group /> to defined groups of key (vowels, consonants, etc);
    - add one or more key <key /> into a key-group with the correct html entity code (if possible, use
    the entity code, not the name).
-->
<keyboard-group>
    <keyboard code="ang">
        <key-group name='capital-vowels'>
            <key id='capital-long-a'>&#256;</key>
            <key id='capital-long-e'>&#274;</key>
            <key id='capital-long-i'>&#298;</key>
            <key id='capital-long-o'>&#332;</key>
            <key id='capital-long-u'>&#362;</key>
            <key id='capital-long-y'>&#562;</key>
            <key id='capital-short-ash'>&#198;</key>
            <key id='capital-long-ash'>&#482;</key>
            <key id='capital-a-acute'>&#193;</key>
            <key id='capital-e-acute'>&#201;</key>
            <key id='capital-i-acute'>&#205;</key>
            <key id='capital-o-acute'>&#211;</key>
            <key id='capital-u-acute'>&#218;</key>
            <key id='capital-y-acute'>&#221;</key>
            <key id='capital-ash-acute'>&#508;</key>
        </key-group>
        <key-group name='lower-vowels'>
            <key id='lower-long-a'>&#257;</key>
            <key id='lower-long-e'>&#275;</key>
            <key id='lower-long-i'>&#299;</key>
            <key id='lower-long-o'>&#333;</key>
            <key id='lower-long-u'>&#363;</key>
            <key id='lower-long-y'>&#563;</key>
            <key id='lower-short-ash'>&#230;</key>
            <key id='lower-long-ash'>&#483;</key>
            <key id='lower-a-acute'>&#225;</key>
            <key id='lower-e-acute'>&#233;</key>
            <key id='lower-i-acute'>&#237;</key>
            <key id='lower-o-acute'>&#243;</key>
            <key id='lower-u-acute'>&#250;</key>
            <key id='lower-y-acute'>&#253;</key>
            <key id='lower-y-with-main-stroke'>&#xF233;</key>
            <key id='lower-ash-acute'>&#509;</key>
        </key-group>
        <key-group name='consonants'>
            <key id='capital-eth'>&#208;</key>
            <key id='lower-eth'>&#240;</key>
            <key id='capital-thorn'>&#222;</key>
            <key id='lower-thorn'>&#254;</key>
            <key id='capital-wynn'>&#503;</key>
            <key id='lower-wynn'>&#447;</key>
            <key id='capital-yogh'>&#540;</key>
            <key id='lower-yogh'>&#541;</key>
            <key id='capital-c-dot'>&#266;</key>
            <key id='lower-c-dot'>&#267;</key>
            <key id='capital-g-dot'>&#288;</key>
            <key id='lower-g-dot'>&#289;</key>
        </key-group>
        <key-group name='manuscript-conventions'>
            <key id='amperagus-tironian-et'>&#8266;</key>
            <key id='thorn-with-slash'>&#42853;</key>
        </key-group>
    </keyboard>
</keyboard-group>
